'use client'

import { type GraphData, type Edge, type Node } from '@/types/graph'
import { Button } from '@/components/ui/button'
import { Download, FileJson, FileCode2, Network } from 'lucide-react'
import { toast } from 'react-hot-toast'

interface ExportTabProps {
  data: GraphData
  transformId: string
}

/**
 * Export tab — three client-side serializers, no backend round-trip.
 *
 * Format choices for PR2:
 *   * JSON — pass-through of the graph payload
 *   * Cypher — CREATE statements suitable for Neo4j / FalkorDB / Memgraph
 *   * GraphML — XML for Gephi, yEd, Cytoscape Desktop
 *
 * Deferred to a future PR (where the value of a heavy dep > 0): JSON-LD,
 * RDF/Turtle (need vocab decisions), Parquet (needs WASM), Arrow.
 */
export function ExportTab({ data, transformId }: ExportTabProps) {
  const counts = `${data.nodes.length} nodes · ${data.edges.length} edges`

  const exporters: ExporterDef[] = [
    {
      id: 'json',
      label: 'JSON',
      description: 'Graphora native format. Roundtrips cleanly.',
      icon: FileJson,
      build: () => ({
        body: JSON.stringify(data, null, 2),
        mime: 'application/json',
        filename: `graphora-${transformId}.json`,
      }),
    },
    {
      id: 'cypher',
      label: 'Cypher',
      description: 'CREATE statements for Neo4j / FalkorDB / Memgraph.',
      icon: FileCode2,
      build: () => ({
        body: serializeCypher(data),
        mime: 'text/plain',
        filename: `graphora-${transformId}.cypher`,
      }),
    },
    {
      id: 'graphml',
      label: 'GraphML',
      description: 'XML — opens in Gephi, yEd, Cytoscape Desktop.',
      icon: Network,
      build: () => ({
        body: serializeGraphML(data),
        mime: 'application/xml',
        filename: `graphora-${transformId}.graphml`,
      }),
    },
  ]

  const handleDownload = (def: ExporterDef) => {
    try {
      const { body, mime, filename } = def.build()
      triggerDownload(body, mime, filename)
      toast.success(`Downloaded ${filename}`)
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      toast.error(`Could not export ${def.label}: ${msg}`)
    }
  }

  return (
    <div className="flex h-full flex-col gap-4 p-6">
      <header>
        <h2 className="text-lg font-semibold">Export</h2>
        <p className="text-sm text-muted-foreground">
          Download the current graph in standard interchange formats.
          Everything is generated in your browser — no backend round-trip.
        </p>
        <p className="mt-1 text-xs text-muted-foreground">{counts}</p>
      </header>

      <div className="grid grid-cols-1 gap-3 md:grid-cols-3">
        {exporters.map((def) => {
          const Icon = def.icon
          return (
            <div
              key={def.id}
              className="flex flex-col rounded-lg border p-4"
              style={{ borderColor: 'var(--line)' }}
            >
              <div className="mb-2 flex items-center gap-2">
                <Icon className="h-5 w-5 text-muted-foreground" />
                <h3 className="text-base font-semibold">{def.label}</h3>
              </div>
              <p className="flex-1 text-sm text-muted-foreground">
                {def.description}
              </p>
              <Button
                variant="outline"
                size="sm"
                className="mt-4"
                onClick={() => handleDownload(def)}
              >
                <Download className="mr-2 h-3.5 w-3.5" />
                Download
              </Button>
            </div>
          )
        })}
      </div>
    </div>
  )
}

interface ExporterDef {
  id: string
  label: string
  description: string
  icon: typeof Download
  build: () => { body: string; mime: string; filename: string }
}

// ---- serializers -----------------------------------------------------------
// Exported for unit testing — the I/O wrapper (triggerDownload) is the
// non-deterministic part; the serialization itself is pure.

export function serializeCypher(data: GraphData): string {
  const lines: string[] = ['// Generated by Graphora Explorer']

  // Nodes — variable name `n_<sanitised id>` so relationship lines
  // can reference them without re-MATCHing.
  for (const node of data.nodes) {
    const varName = cypherIdent(node.id)
    const label = cypherLabel(node.type || 'Node')
    const props = cypherProps({ id: node.id, ...(node.properties || {}) })
    lines.push(`CREATE (${varName}:${label} ${props})`)
  }

  if (data.edges.length > 0) {
    lines.push('')
  }
  for (const edge of data.edges) {
    const fromVar = cypherIdent(edge.source)
    const toVar = cypherIdent(edge.target)
    const relType = cypherRelType(edge.type || edge.label || 'RELATED_TO')
    const props = cypherProps(edge.properties || {})
    lines.push(
      `CREATE (${fromVar})-[:${relType} ${props}]->(${toVar})`
    )
  }

  return lines.join('\n') + '\n'
}

export function serializeGraphML(data: GraphData): string {
  // Emit an attribute key for every distinct property name we see —
  // GraphML requires up-front <key> declarations before the graph body.
  const nodePropKeys = collectPropKeys(data.nodes)
  const edgePropKeys = collectPropKeys(data.edges)

  const out: string[] = []
  out.push('<?xml version="1.0" encoding="UTF-8"?>')
  out.push(
    '<graphml xmlns="http://graphml.graphdrawing.org/xmlns">'
  )
  out.push(
    '  <key id="type" for="node" attr.name="type" attr.type="string"/>'
  )
  out.push(
    '  <key id="label" for="node" attr.name="label" attr.type="string"/>'
  )
  for (const k of nodePropKeys) {
    out.push(
      `  <key id="n_${escapeXml(k)}" for="node" attr.name="${escapeXml(k)}" attr.type="string"/>`
    )
  }
  out.push(
    '  <key id="rel_type" for="edge" attr.name="type" attr.type="string"/>'
  )
  for (const k of edgePropKeys) {
    out.push(
      `  <key id="e_${escapeXml(k)}" for="edge" attr.name="${escapeXml(k)}" attr.type="string"/>`
    )
  }
  out.push('  <graph edgedefault="directed">')

  for (const node of data.nodes) {
    out.push(`    <node id="${escapeXml(node.id)}">`)
    out.push(`      <data key="type">${escapeXml(node.type || '')}</data>`)
    if (node.label) {
      out.push(`      <data key="label">${escapeXml(node.label)}</data>`)
    }
    for (const k of nodePropKeys) {
      const value = (node.properties || {})[k]
      if (value !== undefined && value !== null) {
        out.push(
          `      <data key="n_${escapeXml(k)}">${escapeXml(String(value))}</data>`
        )
      }
    }
    out.push('    </node>')
  }

  for (const edge of data.edges) {
    const id = edge.id || `${edge.source}-${edge.target}`
    out.push(
      `    <edge id="${escapeXml(id)}" source="${escapeXml(edge.source)}" target="${escapeXml(edge.target)}">`
    )
    out.push(
      `      <data key="rel_type">${escapeXml(edge.type || edge.label || '')}</data>`
    )
    for (const k of edgePropKeys) {
      const value = (edge.properties || {})[k]
      if (value !== undefined && value !== null) {
        out.push(
          `      <data key="e_${escapeXml(k)}">${escapeXml(String(value))}</data>`
        )
      }
    }
    out.push('    </edge>')
  }

  out.push('  </graph>')
  out.push('</graphml>')
  return out.join('\n') + '\n'
}

// ---- low-level helpers -----------------------------------------------------

function triggerDownload(body: string, mime: string, filename: string): void {
  const blob = new Blob([body], { type: mime })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  // Revoke after the click handler returns so older browsers don't
  // race the download against URL invalidation.
  setTimeout(() => URL.revokeObjectURL(url), 100)
}

/**
 * Sanitise an arbitrary id into a valid Cypher identifier. Only
 * alphanumerics + underscore survive; everything else is replaced.
 * Prefixed with `n_` so ids that start with digits don't break the
 * parser.
 */
function cypherIdent(id: string): string {
  return 'n_' + id.replace(/[^a-zA-Z0-9_]/g, '_')
}

function cypherLabel(label: string): string {
  // PascalCase'd, alphanumeric only — Neo4j label spec.
  return label.replace(/[^a-zA-Z0-9_]/g, '_') || 'Node'
}

function cypherRelType(type: string): string {
  // SCREAMING_SNAKE_CASE convention — uppercase + alphanumeric +
  // underscore.
  return (type.toUpperCase().replace(/[^A-Z0-9_]/g, '_')) || 'RELATED_TO'
}

function cypherProps(props: Record<string, unknown>): string {
  const entries = Object.entries(props).filter(
    ([, v]) => v !== undefined && v !== null
  )
  if (entries.length === 0) return '{}'
  const body = entries
    .map(([k, v]) => `${cypherKey(k)}: ${cypherValue(v)}`)
    .join(', ')
  return `{${body}}`
}

function cypherKey(key: string): string {
  // Quote the key with backticks if it isn't a bare identifier — keeps
  // hyphens, dots, etc. legal.
  if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key)) return key
  return '`' + key.replace(/`/g, '``') + '`'
}

function cypherValue(value: unknown): string {
  if (typeof value === 'number') return String(value)
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  // Strings + everything else → JSON-ish single-line.
  const text = typeof value === 'string' ? value : JSON.stringify(value)
  // Escape backslashes first so the subsequent quote escape doesn't
  // accidentally produce `\\"`.
  const escaped = text.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
  return `"${escaped}"`
}

function collectPropKeys(items: Array<Node | Edge>): string[] {
  const set = new Set<string>()
  for (const item of items) {
    for (const k of Object.keys(item.properties || {})) {
      set.add(k)
    }
  }
  return Array.from(set).sort()
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}
